name: Release

on:
  workflow_dispatch: ~
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC / npm
  contents: read

jobs:
  build:
    name: 'Build & Publish to NPM'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build
      - name: 'Determine NPM tag: latest or next depending if we are on a prerelease or not (version with hyphen should be a prerelease)'
        id: npm_tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *-* ]]; then
            echo "TAG=next" >> "$GITHUB_OUTPUT"
          else
            echo "TAG=latest" >> "$GITHUB_OUTPUT"
          fi
      - run: cd npm && npm publish --tag ${{ steps.npm_tag.outputs.TAG }}

